# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name          = "empty-jekyll-theme"
  spec.version       = "0.1.1"
  spec.authors       = ["Martin Kopta"]
  spec.email         = ["martin.kopta+empty-jekyll-theme@garcon.cz"]

  spec.summary       = "This Jekyll theme is the default empty Jekyll theme generated by “jeykll new-theme” command."
  spec.homepage      = "https://jekyllrb.com/docs/themes/#creating-a-gem-based-theme"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").select { |f| f.match(%r!^(assets|_layouts|_includes|_sass|LICENSE|README)!i) }

  spec.add_runtime_dependency "jekyll", "~> 3.8"

  spec.add_development_dependency "bundler", "~> 1.16"
  spec.add_development_dependency "rake", "~> 12.0"
end
